// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkomegyeuylyqgshzgup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrb21lZ3lldXlseXFnc2h6Z3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDE3OTcsImV4cCI6MjA1ODQxNzc5N30.7ELHg-gugK_iDxRIai3Kk9Yi_0D9UQrdGh0HmJDt_CY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);